apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meuprimeirocluster
  name: meuprimeirocluster
spec:
  containers:
  - image: nginx
    name: meuprimeirocluster
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}